import pygame

class Const:
  FPS = 60
  WIDTH, HEIGHT = 900, 900

  BG = (210, 205, 202)
  DARK_SQUARE = (223, 197, 170)
  LIGHT_SQUARE = (237, 226, 222)
  BLACK = (0, 0, 0)
  HIGHLIGHT_MOVE = (188, 183, 179)
  HIGHLIGHT_ORIGIN = (148, 140, 137)

  SQUARE_SIZE = 100
  EMPTY = pygame.Rect(0, 0, 0, 0)
  W_KING = pygame.Rect(0, 0, SQUARE_SIZE, SQUARE_SIZE)
  B_KING = pygame.Rect(0, SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE)
  W_QUEEN = pygame.Rect(SQUARE_SIZE, 0, SQUARE_SIZE, SQUARE_SIZE)
  B_QUEEN = pygame.Rect(SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE)
  W_BISHOP = pygame.Rect(2 * SQUARE_SIZE, 0, SQUARE_SIZE, SQUARE_SIZE)
  B_BISHOP = pygame.Rect(2 * SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE)
  W_KNIGHT = pygame.Rect(3 * SQUARE_SIZE, 0, SQUARE_SIZE, SQUARE_SIZE)
  B_KNIGHT = pygame.Rect(3 * SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE)
  W_ROOK = pygame.Rect(4 * SQUARE_SIZE, 0, SQUARE_SIZE, SQUARE_SIZE)
  B_ROOK = pygame.Rect(4 * SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE)
  W_PAWN = pygame.Rect(5 * SQUARE_SIZE, 0, SQUARE_SIZE, SQUARE_SIZE)
  B_PAWN = pygame.Rect(5 * SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE)
